name: Flutter Linux Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Linux dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.0'
        channel: 'stable'
    
    - name: Enable Linux desktop
      run: flutter config --enable-linux-desktop
    
    - name: Create Linux configuration if not exists
      run: |
        if [ ! -d "linux" ]; then
          echo "Linux configuration not found. Generating..."
          flutter create --platforms=linux .
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Add Linux configuration files"
          git push
        else
          echo "Linux configuration found."
        fi
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Build Linux app
      run: flutter build linux --release
    
    - name: Archive Linux build
      uses: actions/upload-artifact@v3
      with:
        name: linux-build
        path: build/linux/x64/release/bundle
