name: Flutter Linux Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable' # You can specify a version like '3.10.1'

    - name: Install dependencies
      run: flutter pub get

    - name: Run Flutter Linux build
      run: flutter build linux

    - name: Archive build
      uses: actions/upload-artifact@v3
      with:
        name: linux-build
        path: build/linux/ # specify the folder where your binary is created
